const CHAR_DB = [
    // 金 (Gold)
    { char: '瑞', pinyin: 'ruì', element: '金', strokes: 14, meaning: '吉祥，好预兆' },
    { char: '诚', pinyin: 'chéng', element: '金', strokes: 14, meaning: '真实，真心' },
    { char: '锦', pinyin: 'jǐn', element: '金', strokes: 16, meaning: '鲜明，美丽' },
    { char: '锋', pinyin: 'fēng', element: '金', strokes: 15, meaning: '锐利，锋芒' },
    { char: '铭', pinyin: 'míng', element: '金', strokes: 14, meaning: '铭记，刻写' },
    { char: '诗', pinyin: 'shī', element: '金', strokes: 13, meaning: '诗歌，文雅' },
    { char: '悦', pinyin: 'yuè', element: '金', strokes: 11, meaning: '高兴，愉快' },
    { char: '钰', pinyin: 'yù', element: '金', strokes: 13, meaning: '珍宝，坚硬的金属' },
    { char: '修', pinyin: 'xiū', element: '金', strokes: 10, meaning: '修养，整治' },
    { char: '承', pinyin: 'chéng', element: '金', strokes: 8, meaning: '承担，继承' },
    { char: '初', pinyin: 'chū', element: '金', strokes: 7, meaning: '开始，原来' },
    { char: '锦', pinyin: 'jǐn', element: '金', strokes: 16, meaning: '前程似锦' },
    { char: '鑫', pinyin: 'xīn', element: '金', strokes: 24, meaning: '财富兴旺' },
    { char: '星', pinyin: 'xīng', element: '金', strokes: 9, meaning: '星辰，明亮' },
    { char: '晨', pinyin: 'chén', element: '金', strokes: 11, meaning: '清晨，希望' },

    // 木 (Wood)
    { char: '杰', pinyin: 'jié', element: '木', strokes: 8, meaning: '杰出，才智' },
    { char: '松', pinyin: 'sōng', element: '木', strokes: 8, meaning: '松树，坚毅' },
    { char: '林', pinyin: 'lín', element: '木', strokes: 8, meaning: '树林，繁荣' },
    { char: '柏', pinyin: 'bǎi', element: '木', strokes: 9, meaning: '柏树，长寿' },
    { char: '栋', pinyin: 'dòng', element: '木', strokes: 12, meaning: '栋梁，重任' },
    { char: '艺', pinyin: 'yì', element: '木', strokes: 21, meaning: '才艺，技能' },
    { char: '菲', pinyin: 'fēi', element: '木', strokes: 14, meaning: '花草香，美丽' },
    { char: '萱', pinyin: 'xuān', element: '木', strokes: 15, meaning: '忘忧草' },
    { char: '欣', pinyin: 'xīn', element: '木', strokes: 8, meaning: '快乐，喜欢' },
    { char: '佳', pinyin: 'jiā', element: '木', strokes: 8, meaning: '美好，优秀' },
    { char: '梦', pinyin: 'mèng', element: '木', strokes: 11, meaning: '梦想，希望' },
    { char: '楠', pinyin: 'nán', element: '木', strokes: 13, meaning: '珍贵木材' },
    { char: '月', pinyin: 'yuè', element: '木', strokes: 4, meaning: '月亮，柔美' },
    { char: '语', pinyin: 'yǔ', element: '木', strokes: 14, meaning: '语言，表达' },
    { char: '梓', pinyin: 'zǐ', element: '木', strokes: 11, meaning: '故乡，生机' },

    // 水 (Water)
    { char: '涵', pinyin: 'hán', element: '水', strokes: 12, meaning: '包容，涵养' },
    { char: '泽', pinyin: 'zé', element: '水', strokes: 17, meaning: '恩泽，光泽' },
    { char: '浩', pinyin: 'hào', element: '水', strokes: 11, meaning: '浩大，广阔' },
    { char: '清', pinyin: 'qīng', element: '水', strokes: 11, meaning: '清澈，洁净' },
    { char: '渊', pinyin: 'yuān', element: '水', strokes: 12, meaning: '深渊，学识深' },
    { char: '洁', pinyin: 'jié', element: '水', strokes: 10, meaning: '纯洁，高尚' },
    { char: '润', pinyin: 'rùn', element: '水', strokes: 16, meaning: '滋润，柔和' },
    { char: '涛', pinyin: 'tāo', element: '水', strokes: 18, meaning: '波涛，气势' },
    { char: '冰', pinyin: 'bīng', element: '水', strokes: 6, meaning: '冰雪，纯净' },
    { char: '雯', pinyin: 'wén', element: '水', strokes: 12, meaning: '彩云，美丽' },
    { char: '海', pinyin: 'hǎi', element: '水', strokes: 11, meaning: '大海，宽广' },
    { char: '洋', pinyin: 'yáng', element: '水', strokes: 10, meaning: '海洋，广阔' },
    { char: '源', pinyin: 'yuán', element: '水', strokes: 14, meaning: '源头，根本' },
    { char: '洛', pinyin: 'luò', element: '水', strokes: 10, meaning: '洛水，繁华' },
    { char: '云', pinyin: 'yún', element: '水', strokes: 4, meaning: '云彩，高远' },

    // 火 (Fire)
    { char: '灿', pinyin: 'càn', element: '火', strokes: 17, meaning: '灿烂，光辉' },
    { char: '炎', pinyin: 'yán', element: '火', strokes: 8, meaning: '炎热，热情' },
    { char: '灵', pinyin: 'líng', element: '火', strokes: 24, meaning: '灵巧，聪明' },
    { char: '煜', pinyin: 'yù', element: '火', strokes: 13, meaning: '照耀，光辉' },
    { char: '烁', pinyin: 'shuò', element: '火', strokes: 19, meaning: '闪烁，明亮' },
    { char: '彤', pinyin: 'tóng', element: '火', strokes: 7, meaning: '红色，热烈' },
    { char: '昕', pinyin: 'xīn', element: '火', strokes: 8, meaning: '黎明，希望' },
    { char: '宁', pinyin: 'níng', element: '火', strokes: 14, meaning: '安宁，平和' },
    { char: '智', pinyin: 'zhì', element: '火', strokes: 12, meaning: '智慧，聪明' },
    { char: '昭', pinyin: 'zhāo', element: '火', strokes: 9, meaning: '昭示，明白' },
    { char: '烨', pinyin: 'yè', element: '火', strokes: 10, meaning: '光辉，灿烂' },
    { char: '然', pinyin: 'rán', element: '火', strokes: 12, meaning: '自然，信守' },
    { char: '熙', pinyin: 'xī', element: '火', strokes: 13, meaning: '光明，兴起' },
    { char: '明', pinyin: 'míng', element: '火', strokes: 8, meaning: '明亮，清楚' },
    { char: '阳', pinyin: 'yáng', element: '火', strokes: 17, meaning: '阳光，积极' },

    // 土 (Earth)
    { char: '宇', pinyin: 'yǔ', element: '土', strokes: 6, meaning: '宇宙，气度' },
    { char: '轩', pinyin: 'xuān', element: '土', strokes: 10, meaning: '高扬，气宇' },
    { char: '远', pinyin: 'yuǎn', element: '土', strokes: 17, meaning: '长远，深远' },
    { char: '磊', pinyin: 'lěi', element: '土', strokes: 15, meaning: '光明磊落' },
    { char: '坤', pinyin: 'kūn', element: '土', strokes: 8, meaning: '大地，宽厚' },
    { char: '怡', pinyin: 'yí', element: '土', strokes: 9, meaning: '快乐，和悦' },
    { char: '韵', pinyin: 'yùn', element: '土', strokes: 19, meaning: '韵味，情趣' },
    { char: '安', pinyin: 'ān', element: '土', strokes: 6, meaning: '平安，安定' },
    { char: '岚', pinyin: 'lán', element: '土', strokes: 12, meaning: '山间雾气' },
    { char: '逸', pinyin: 'yì', element: '土', strokes: 15, meaning: '安逸，超凡' },
    { char: '山', pinyin: 'shān', element: '土', strokes: 3, meaning: '稳重，依靠' },
    { char: '岩', pinyin: 'yán', element: '土', strokes: 8, meaning: '坚强，坚定' },
    { char: '圣', pinyin: 'shèng', element: '土', strokes: 13, meaning: '圣贤，崇高' },
    { char: '勋', pinyin: 'xūn', element: '土', strokes: 16, meaning: '功勋，成就' },
    { char: '伟', pinyin: 'wěi', element: '土', strokes: 11, meaning: '伟大，宏大' }
];

const I_CHING_DATA = {
    // 简化的周易卦象解释
    '111111': { name: '乾为天', meaning: '元亨利贞，刚健中正，自强不息。' },
    '000000': { name: '坤为地', meaning: '厚德载物，柔顺伸展，广纳包容。' },
    '101010': { name: '既济', meaning: '阴阳调和，功德圆满，平安吉祥。' },
    '010101': { name: '未济', meaning: '充满希望，不断进取，前途无量。' },
    '100000': { name: '复卦', meaning: '万物更新，生机勃勃，重获新生。' },
    '000001': { name: '剥卦', meaning: '顺势而为，积蓄力量，待机而动。' },
    '111000': { name: '泰卦', meaning: '天地交泰，万物通畅，安泰吉祥。' },
    '000111': { name: '否卦', meaning: '韬光养晦，静待时机，不可妄动。' },
};
